### ISSUE TITLE
I got a problem trying to adapt your code

### ISSUE THREAD

**Issue by cxwong919** [erizmr/taichi_ray_tracing#2]
Your code is beautifully written, and I'm trying to learn Taichi by reading your code. I have a problem when trying to adapt your code.

Here is your original code I tried to adapt in "ray_tracing_models.py":

> 
    @ti.data_oriented
    class Sphere:
    def __init__(self, center, radius, material, color):
        self.center = center
        self.radius = radius
        self.material = material
        self.color = color
    @ti.func
    def hit(self, ray, t_min=0.001, t_max=10e8):
        oc = ray.origin - self.center
        a = ray.direction.dot(ray.direction)
        b = 2.0 * oc.dot(ray.direction)
        c = oc.dot(oc) - self.radius * self.radius
        discriminant = b * b - 4 * a * c
        is_hit = False
        front_face = False
        root = 0.0
        hit_point =  ti.Vector([0.0, 0.0, 0.0])
        hit_point_normal = ti.Vector([0.0, 0.0, 0.0])
        if discriminant > 0:
            sqrtd = ti.sqrt(discriminant)
            root = (-b - sqrtd) / (2 * a)
            if root < t_min or root > t_max:
                root = (-b + sqrtd) / (2 * a)
                if root >= t_min and root <= t_max:
                    is_hit = True
            else:
                is_hit = True
        if is_hit:
            hit_point = ray.at(root)
            hit_point_normal = (hit_point - self.center) / self.radius
            # Check which side does the ray hit, we set the hit point normals always point outward from the surface
            if ray.direction.dot(hit_point_normal) < 0:
                front_face = True
            else:
                hit_point_normal = -hit_point_normal
        return is_hit, root, hit_point, hit_point_normal, front_face, self.material, self.color

I tried to replace it with:

> 
    @ti.data_oriented
    class Arrows:
    def __init__(self, center, normal, vertices, material, color):
        self.center = center
        self.normal = normal
        self.verti = vertices
        self.material = material
        self.color = color
    @ti.func
    def hit(self, ray, t_min=0.001, t_max=10e8):
        is_hit = False
        front_face = False
        root = 0.0
        hit_point =  ti.Vector([0.0, 0.0, 0.0])
        hit_point_normal = ti.Vector([0.0, 0.0, 0.0])
        for i in ti.static(range(27)):
            ver = ti.Vector(self.verti[i,:])
            root = -ray.origin.dot(self.normal)/ray.direction.dot(self.normal)
            hit_point = ray.at(root)
            vec0 = (self.center - hit_point).normalized()
            vec = (ver - hit_point).normalized()
            if ti.static(vec0.dot(vec) <= 0):
                is_hit = True
        if is_hit:
            hit_point = ray.at(root)
            hit_point_normal = (hit_point - self.center) / (hit_point - self.center).norm()
            # Check which side does the ray hit, we set the hit point normals always point outward from the surface
            if ray.direction.dot(hit_point_normal) < 0:
                front_face = True
            else:
                hit_point_normal = -hit_point_normal
        return is_hit, root, hit_point, hit_point_normal, front_face, self.material, self.color

In "1_0_color_only.py" subsequently, these lines:

>  
    scene.add(Sphere(center=ti.Vector([0, 5.4, -1]), radius=3.0, material=0, color=ti.Vector([10.0, 10.0, 10.0])))
    scene.add(Sphere(center=ti.Vector([0, -100.5, -1]), radius=100.0, material=1, color=ti.Vector([0.8, 0.8, 0.8])))
    scene.add(Sphere(center=ti.Vector([0, 102.5, -1]), radius=100.0, material=1, color=ti.Vector([0.8, 0.8, 0.8])))
    scene.add(Sphere(center=ti.Vector([0, 1, 101]), radius=100.0, material=1, color=ti.Vector([0.8, 0.8, 0.8])))
    scene.add(Sphere(center=ti.Vector([-101.5, 0, -1]), radius=100.0, material=1, color=ti.Vector([0.6, 0.0, 0.0])))
    scene.add(Sphere(center=ti.Vector([101.5, 0, -1]), radius=100.0, material=1, color=ti.Vector([0.0, 0.6, 0.0])))
    scene.add(Sphere(center=ti.Vector([0, -0.2, -1.5]), radius=0.3, material=1, color=ti.Vector([0.8, 0.3, 0.3])))
    scene.add(Sphere(center=ti.Vector([-0.8, 0.2, -1]), radius=0.7, material=2, color=ti.Vector([0.6, 0.8, 0.8])))
    scene.add(Sphere(center=ti.Vector([0.7, 0, -0.5]), radius=0.5, material=3, color=ti.Vector([1.0, 1.0, 1.0])))
    scene.add(Sphere(center=ti.Vector([0.6, -0.3, -2.0]), radius=0.2, material=4, color=ti.Vector([0.8, 0.6, 0.2])))

are replaced with:

> 
    for n,i in ti.ndrange(num_arrows,num_planes_single):
        scene.add(Arrows(center=ti.Vector(cen_coor[n,i,:]), normal=ti.Vector(nor_coor[n,i,:]), vertices=vert_coor[n,:,:], material=1, color=ti.Vector(color_default[n,i,:])))

Then I received this error message:

> 
    TaichiCompilationError                    Traceback (most recent call last)
    Input In [5], in <cell line: 92>()
    136 cnt = 0
    137 while gui.running:
    --> 138     render()
    139     cnt += 1
    140     gui.set_image(np.sqrt(canvas.to_numpy() / cnt))
    File ~\anaconda3\envs\chenxi\lib\site-packages\taichi\lang\kernel_impl.py:976, in _kernel_impl.<locals>.wrapped(*args, **kwargs)
    974     return primal(*args, **kwargs)
    975 except (TaichiCompilationError, TaichiRuntimeError) as e:
    --> 976     raise type(e)('\n' + str(e)) from None

    TaichiCompilationError: 
    File "C:\Users\MMIL\AppData\Local\Temp\ipykernel_17744\1754333432.py", line 27, in render:
            color += ray_color(ray)
                     ^^^^^^^^^^^^^^
    File "C:\Users\MMIL\AppData\Local\Temp\ipykernel_17744\1754333432.py", line 42, in ray_color:
        is_hit, hit_point, hit_point_normal, front_face, material, color =
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\MMIL\Chenxi\VTK - Accumulative switching\ray_tracing_models.py", line 144, in hit:
            is_hit_tmp, root_tmp, hit_point_tmp, hit_point_normal_tmp,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\MMIL\Chenxi\VTK - Accumulative switching\ray_tracing_models.py", line 111, in hit:
            if ti.static(vec0.dot(vec) <= 0):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Traceback (most recent call last):
      File "C:\Users\MMIL\anaconda3\envs\wong\lib\site-packages\taichi\lang\ast\ast_transformer_utils.py", line 25, in __call__
    return method(ctx, node)
      File "C:\Users\MMIL\anaconda3\envs\wong\lib\site-packages\taichi\lang\ast\ast_transformer.py", line 549, in build_Call
    node.ptr = func(*args, **keywords)
      File "C:\Users\MMIL\anaconda3\envs\wong\lib\site-packages\taichi\lang\impl.py", line 1030, in static
    raise ValueError(
    ValueError: Input to ti.static must be compile-time constants or global pointers, instead of <class 'taichi.lang.expr.Expr'>

I tried many times to but failed... Do you have any idea what I can do with it? I'd appreciate if you could share your opinion.

Best regards!

**Comment by cxwong919** [comment]
I figured it out somehow
